### ISSUE TITLE
Potential rounding issues decoding from json

### ISSUE THREAD

**Issue by craigrushforth** [Flight-School/Money#8]
This is a fantastic piece of work by the way @mattt and has saved us from having to roll our own solution.

I did discover what could be a potential rounding issue when decoding Decimal's from json.  I'm seeing the following test fail

<img width="963" alt="Screen Shot 2020-04-30 at 3 47 53 PM" src="https://user-images.githubusercontent.com/4520946/80763047-e7954d00-8afa-11ea-97b1-72416e96f5af.png">

Our solution to this was to perform the same rounding correction you already perform elsewhere in the code and add it to the decode function.

E.g.

```
self.amount = Money<Currency>(amount).rounded.amount
```

So the decode method becomes

<img width="1189" alt="Screen Shot 2020-04-30 at 3 59 13 PM" src="https://user-images.githubusercontent.com/4520946/80763380-9f2a5f00-8afb-11ea-84c8-84eafca4ee7b.png">

Just thought I'd mention this incase I'm doing something dumb or it isn't dumb and could be useful to someone else.

I have one other question.  We'd like to override the behaviour of the encode and decode functions to support decoding from a string and encoding to a single value and not the amount + currency (currently we're only using a single currency, but that could change down the line)

How can I extend or override these methods without forking the repo or plain copying your class?  It seems as though you can't inherit from a generic class and override in the usual way.

Anyway thanks again for making this :+1:

**Comment by mattt** [comment]
Thank you for the kind words, @craigrushforth. I'm really glad to hear that this has been helpful for you.

And thanks for filing this issue. The underlying problem is that Swift / Foundation incorrectly decodes `Decimal` values from JSON ([SR-7054](https://bugs.swift.org/browse/SR-7054)). This is related to, but distinct from the problem with floating-point literals discussed in the README.

I remain hopeful that this will be resolved in an upcoming release of Swift, but [this seems unlikely](https://bugs.swift.org/browse/SR-7054?focusedCommentId=50553&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-50553). But until then, I think there are a few things we can do here:

- At the very least, we should absolutely document this in the README.
- Ideally, we could work around the loss of precision by converting to an intermediate `String` representation, but that doesn't seem possible...
- We should probably update the implementation of `init(from:)` to support `Decimal` initialization from strings.
- We could consider adding `CodingUserInfoKey` constants to define behavior (e.g. `round` or `throw`); I think your proposed behavior of rounding, if implemented, should be opt-in through this kind of a mechanism.

If you don't mind waiting, I'm confident that this can be fixed in the mainline repository within a week or two. If you have a more pressing need, I'd suggest pointing your app to your fork rather than attempting to monkey-patch.

**Comment by mattt** [comment]
As a first step, I've opened a draft PR (#9) with several new, failing test cases.

**Comment by craigrushforth** [comment]
This is great news @mattt.  I think we're fine to hold off and wait for a fix in the mainline repo.  I super appreciate this.

**Comment by mattt** [comment]
@craigrushforth After giving this some thought, I decided that the best solution would be to keep the current behavior unchanged, but allow the decoding behavior of `Money` to be configurable via the `userInfo` property of decoders:

https://github.com/Flight-School/Money/pull/9/commits/9270b1bf067fb8e597762f084fc83302950ded8f#diff-8aadd3a3f4af2c691462ae6e87288bdbR207-R250

What do you think?

**Comment by craigrushforth** [comment]
@mattt I haven't pulled this branch or ran any tests or anything but this is great. I like that we can configure the decoding exactly how we'd like it.  I'm probably get ahead of things but do you have plans for `EncodingOptions`?  It would be superb if you could configure the encoding to support both types below:

```
"total" " {
     "amount": 123.12
    "currency: "USD"
}
```

& 

For when you only support a single currency (we currently have to work with a API that is out of our control and can't be modified)
```
{ "total": 123.12 }
```

I really appreciate your time and effort on this.

**Comment by mattt** [comment]
@craigrushforth In fact, that's exactly what I was working on next. I'm happy to say that this is now  also ready for review with d0f6a9c7d88ae48c767cce0b9f842b5287e27260

```swift
var encoder = JSONEncoder()
encoder.moneyEncodingOptions = [.omitCurrency, .encodeAmountAsString]
```

**Comment by craigrushforth** [comment]
https://media3.giphy.com/media/3o7aCWJavAgtBzLWrS/giphy.gif?cid=ecf05e4720e215bf98f9d577db22e444f60c1e60441a647a&rid=giphy.gif

Looks great to me.

Once this is all merged, I'll rip out my modified version and give it a real test. Looks great though.

I wasn't aware you could  add custom encoding/decoding options in this way so I've also learnt something new :+1:

**Comment by mattt** [comment]
@craigrushforth Alright, this is now merged into master as part of the 1.2.0 release. Thanks for your help identifying this and providing feedback!

**Comment by craigrushforth** [comment]
@mattt  I'm still seeing `1.1.1` when doing a `pod install --repo-update` and attempting to force the version to `1.2.0` I get this

<img width="1103" alt="Screen Shot 2020-05-06 at 2 26 33 PM" src="https://user-images.githubusercontent.com/4520946/81226372-fd49bd00-8fa7-11ea-96b2-680918cbad59.png">

Does it usually take some time for it to appear in cocoapods?

**Comment by mattt** [comment]
@craigrushforth Sorry about that. I had TravisCI set up to automatically push updated pod specs for new tags, but that didn't happen. I just did a `pod trunk push` manually, which appears to have gone through: https://cocoapods.org/pods/Money-FlightSchool
